const STORAGE_KEY='crestie-lineage-v1';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const uid=()=>`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
const today=()=>new Date().toISOString().slice(0,10);
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const pct=n=>`${(n*100).toFixed(n*100<10?1:0).replace('.0','')}%`;
let currentView='dashboard', growthSelectedGecko='', pedigreeSelectedId='', pedigreeScale=1;
const state=loadState(); growthSelectedGecko=state.geckos[0]?.id||'';

function normalizeGecko(g={}){return{...g,id:g.id||uid(),name:g.name||'',morph:g.morph||'',sex:['male','female','unknown'].includes(g.sex)?g.sex:'unknown',hatchDate:g.hatchDate||'',acquiredDate:g.acquiredDate||'',breeder:g.breeder||'',notes:g.notes||'',parent1Id:g.parent1Id||'',parent2Id:g.parent2Id||'',breederNotation:g.breederNotation||'',customTraits:Array.isArray(g.customTraits)?g.customTraits:[],genetics:{lilly:g.genetics?.lilly||'unknown',axanthic:g.genetics?.axanthic||'unknown',cappuccino:g.genetics?.cappuccino||'unknown',solidBack:g.genetics?.solidBack||'unknown'}}}
function loadState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');return{geckos:Array.isArray(p.geckos)?p.geckos.map(normalizeGecko):[],growth:Array.isArray(p.growth)?p.growth:[],pairings:Array.isArray(p.pairings)?p.pairings:[]}}catch{return{geckos:[],growth:[],pairings:[]}}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function getGecko(id){return state.geckos.find(g=>g.id===id)}
function geckoName(id){return getGecko(id)?.name||'미등록'}
function sexLabel(s){return({male:'수컷',female:'암컷',unknown:'미확인'})[s]||'미확인'}
function sexBadge(s){return `<span class="badge ${s}">${sexLabel(s)}</span>`}
function statusLabel(s){return({planned:'계획',paired:'교배 진행',eggs:'산란 / 알',hatched:'부화 확인',closed:'종료'})[s]||s}
function splitTraits(v){return v.split(',').map(x=>x.trim()).filter(Boolean)}
function fmtDate(v){return v||'-'}
function ageText(d){if(!d)return'-';const a=new Date(d+'T00:00:00'),n=new Date();let m=(n.getFullYear()-a.getFullYear())*12+n.getMonth()-a.getMonth()-(n.getDate()<a.getDate()?1:0);if(m<0)return'-';return m<12?`${m}개월`:`${Math.floor(m/12)}년 ${m%12}개월`}
function latestGrowth(id){return state.growth.filter(r=>r.geckoId===id).sort((a,b)=>b.date.localeCompare(a.date))[0]}
function isAncestor(a,n,seen=new Set()){if(!a||!n||seen.has(n))return false;seen.add(n);const g=getGecko(n);if(!g)return false;const ps=[g.parent1Id,g.parent2Id].filter(Boolean);return ps.includes(a)||ps.some(p=>isAncestor(a,p,seen))}
function ancestorsOf(id,out=new Set()){const g=getGecko(id);if(!g)return out;[g.parent1Id,g.parent2Id].filter(Boolean).forEach(p=>{if(!out.has(p)){out.add(p);ancestorsOf(p,out)}});return out}
function relationOf(a,b){if(!a||!b)return'두 개체를 선택하세요.';if(a===b)return'같은 개체';const A=getGecko(a),B=getGecko(b);if([A?.parent1Id,A?.parent2Id].includes(b)||[B?.parent1Id,B?.parent2Id].includes(a))return'직계 부모 · 자식';const ap=[A?.parent1Id,A?.parent2Id].filter(Boolean),bp=[B?.parent1Id,B?.parent2Id].filter(Boolean);if(ap.some(x=>bp.includes(x)))return'형제 · 자매';const aa=ancestorsOf(a),bb=ancestorsOf(b);if(aa.has(b)||bb.has(a))return'직계 조상 · 후손';if([...aa].some(x=>bb.has(x)))return'공통 조상이 있는 혈연';return'확인된 공통 조상 없음'}

const viewMeta={dashboard:['대시보드','크레스티드 게코의 성장과 혈통을 한곳에서 관리합니다.'],geckos:['개체 관리','기본 정보와 유전 정보를 관리합니다.'],growth:['성장 기록','날짜별 체중과 전장 변화를 기록합니다.'],pedigree:['교배 · 가계도','부모 관계를 기준으로 자동 배치합니다.'],genetics:['유전 · 교배 예상','두 마리를 선택해 예상 자손을 계산합니다.'],backup:['백업 · 복원','JSON으로 저장하고 불러옵니다.']};
function setView(v){currentView=v;$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${v}`));$('#viewTitle').textContent=viewMeta[v][0];$('#viewSubtitle').textContent=viewMeta[v][1];renderCurrent()}
function renderCurrent(){({dashboard:renderDashboard,geckos:renderGeckos,growth:renderGrowth,pedigree:renderPedigree,genetics:renderGenetics,backup:renderBackup})[currentView]?.()}
function renderAll(){saveState();renderCurrent()}
function emptyHtml(a,b=''){return `<div class="empty"><b>${a}</b><span>${b}</span></div>`}

function renderDashboard(){const latest=[...state.growth].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);$('#view-dashboard').innerHTML=`<div class="grid cols-4"><div class="card stat-card"><div class="stat-label">등록 개체</div><div class="stat-value">${state.geckos.length}</div><div class="stat-sub">전체 개체</div></div><div class="card stat-card"><div class="stat-label">성별 미확인</div><div class="stat-value">${state.geckos.filter(g=>g.sex==='unknown').length}</div><div class="stat-sub">양쪽 성별 교배 후보</div></div><div class="card stat-card"><div class="stat-label">성장 기록</div><div class="stat-value">${state.growth.length}</div><div class="stat-sub">누적 측정</div></div><div class="card stat-card"><div class="stat-label">교배 기록</div><div class="stat-value">${state.pairings.length}</div><div class="stat-sub">계획 포함</div></div></div><div class="grid cols-2" style="margin-top:18px"><div class="card pad"><div class="section-head"><div><h2>최근 성장 기록</h2></div></div>${latest.length?`<div class="list">${latest.map(r=>`<div class="list-item"><div class="list-main"><b>${esc(geckoName(r.geckoId))}</b><span>${r.date}</span></div><span class="badge">${r.weight!==''?r.weight+' g':'-'}</span></div>`).join('')}</div>`:emptyHtml('아직 기록이 없습니다.')}</div><div class="card pad"><div class="section-head"><div><h2>빠른 이동</h2><p>유전 계산은 두 개체만 선택해서 확인합니다.</p></div></div><div class="toolbar"><button class="btn primary" data-go="genetics">유전 · 교배 예상</button><button class="btn secondary" data-go="pedigree">가계도 보기</button></div></div></div>`;$$('[data-go]').forEach(b=>b.onclick=()=>setView(b.dataset.go))}

function comboAliasesForGecko(g){const d=geneProfile(g),out=[];if(d.lilly===1&&d.axanthic===2)out.push('릴리아잔틱','릴잔틱','릴리 아잔틱','Lilly White Axanthic');if(d.lilly===1&&g.genetics.solidBack==='present')out.push('솔리드릴리','솔리드 릴리','솔리드백 릴리','솔리드백 릴리화이트','Solid Lilly');if(d.lilly===1&&d.cappuccino===1)out.push('프라푸치노','Frappuccino');if(!out.length){if(d.lilly===1)out.push('릴리화이트','릴리','Lilly White');if(d.axanthic===2)out.push('아잔틱','Axanthic');if(d.cappuccino===1)out.push('카푸치노','Cappuccino');if(g.genetics.solidBack==='present')out.push('솔리드백','Solid Back')}return [...new Set(out)]}
function geneProfile(g){return{lilly:explicitCopies(g,'lilly'),axanthic:explicitCopies(g,'axanthic'),cappuccino:explicitCopies(g,'cappuccino')}}
function explicitCopies(g,gene){const v=g?.genetics?.[gene];if(gene==='axanthic')return v==='visual'?2:v==='het100'?1:v==='clear'?0:null;return v==='super'?2:(v==='lilly'||v==='cappuccino')?1:v==='normal'?0:null}
function geneticAssessment(g){const certain=[],possible=[];const add=(name,dist)=>{const ks=Object.entries(dist).filter(([,p])=>p>0);if(ks.length===1){const [k]=ks[0];certain.push(labelGeneState(name,+k))}else ks.forEach(([k,p])=>possible.push(`${labelGeneState(name,+k)} ${pct(p)}`))};['lilly','axanthic','cappuccino'].forEach(x=>add(x,geneDist(g,x)));if(g.genetics.solidBack==='present')certain.push('솔리드백');else if(g.genetics.solidBack==='unknown')possible.push('솔리드백 여부 미확인');return{certain,possible}}
function labelGeneState(g,c){if(g==='lilly')return c===2?'슈퍼 릴리':c===1?'릴리화이트':'릴리 유전자 없음';if(g==='axanthic')return c===2?'비주얼 아잔틱':c===1?'헷 아잔틱':'아잔틱 유전자 없음';return c===2?'슈퍼 카푸치노':c===1?'카푸치노':'카푸치노 유전자 없음'}

function renderGeckos(){const rows=state.geckos.map(g=>{const a=geneticAssessment(g),aliases=comboAliasesForGecko(g);return `<tr><td class="name-cell"><b>${esc(g.name)}</b><span>${esc(g.morph||'모프 미입력')}</span></td><td class="name-cell"><b>${esc(aliases[0]||a.certain.slice(0,2).join(' · ')||'-')}</b><span>${esc(aliases.slice(1).join(' / ')||a.possible.slice(0,2).join(' · ')||'')}</span></td><td>${sexBadge(g.sex)}</td><td>${latestGrowth(g.id)?.weight??'-'}${latestGrowth(g.id)?.weight!=null?' g':''}</td><td>${esc(geckoName(g.parent1Id))}</td><td>${esc(geckoName(g.parent2Id))}</td><td><div class="actions"><button class="btn secondary small" data-edit="${g.id}">수정</button><button class="btn ghost small" data-growth="${g.id}">성장</button><button class="btn ghost small" data-del="${g.id}">삭제</button></div></td></tr>`}).join('');$('#view-geckos').innerHTML=`<div class="card"><div class="section-head" style="padding:18px 18px 0"><div><h2>개체 목록</h2><p>부모·유전 정보를 수정하면 계산 결과도 갱신됩니다.</p></div><button class="btn primary" id="addGeckoInView">+ 개체 등록</button></div>${rows?`<div class="table-wrap"><table><thead><tr><th>개체</th><th>유전 / 통용 표기</th><th>성별</th><th>최근 체중</th><th>부모 1</th><th>부모 2</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>`:emptyHtml('등록된 개체가 없습니다.')}</div>`;$('#addGeckoInView').onclick=()=>openGeckoDialog();$$('[data-edit]').forEach(b=>b.onclick=()=>openGeckoDialog(b.dataset.edit));$$('[data-growth]').forEach(b=>b.onclick=()=>{growthSelectedGecko=b.dataset.growth;setView('growth')});$$('[data-del]').forEach(b=>b.onclick=()=>deleteGecko(b.dataset.del))}
function fillGeckoSelect(el,{includeBlank=false,excludeId=''}={}){el.innerHTML=(includeBlank?'<option value="">없음 / 미등록</option>':'')+state.geckos.filter(g=>g.id!==excludeId).map(g=>`<option value="${g.id}">${esc(g.name)} · ${sexLabel(g.sex)}</option>`).join('')}
function openGeckoDialog(id=''){const g=id?getGecko(id):null;$('#geckoDialogTitle').textContent=g?'개체 정보 수정':'개체 등록';$('#geckoId').value=g?.id||'';$('#geckoName').value=g?.name||'';$('#geckoMorph').value=g?.morph||'';$('#geckoSex').value=g?.sex||'unknown';$('#geckoHatchDate').value=g?.hatchDate||'';$('#geckoAcquiredDate').value=g?.acquiredDate||'';$('#geckoBreeder').value=g?.breeder||'';$('#geckoNotes').value=g?.notes||'';$('#geckoNotation').value=g?.breederNotation||'';$('#geckoTraits').value=(g?.customTraits||[]).join(', ');$('#geneLilly').value=g?.genetics?.lilly||'unknown';$('#geneAxanthic').value=g?.genetics?.axanthic||'unknown';$('#geneCappuccino').value=g?.genetics?.cappuccino||'unknown';$('#traitSolidBack').value=g?.genetics?.solidBack||'unknown';fillGeckoSelect($('#geckoParent1'),{includeBlank:true,excludeId:id});fillGeckoSelect($('#geckoParent2'),{includeBlank:true,excludeId:id});$('#geckoParent1').value=g?.parent1Id||'';$('#geckoParent2').value=g?.parent2Id||'';$('#notationHint').textContent='';$('#geckoFormError').classList.add('hidden');$('#geckoDialog').showModal()}
function analyzeNotation(){const t=($('#geckoNotation').value+' '+$('#geckoMorph').value).toLowerCase().replace(/\s/g,'');let found=[];if(/릴잔틱|릴리아잔틱|lillywhiteaxanthic/.test(t)){ $('#geneLilly').value='lilly';$('#geneAxanthic').value='visual';found.push('릴리화이트 + 비주얼 아잔틱') }else if(/릴리|lillywhite/.test(t)){ $('#geneLilly').value='lilly';found.push('릴리화이트') }if(/100%?헷아잔틱|100hetaxanthic/.test(t)){ $('#geneAxanthic').value='het100';found.push('100% 헷 아잔틱') }else if(/66%?헷아잔틱/.test(t)){ $('#geneAxanthic').value='het66';found.push('66% 헷 아잔틱') }else if(/50%?헷아잔틱/.test(t)){ $('#geneAxanthic').value='het50';found.push('50% 헷 아잔틱') }else if(/아잔틱|axanthic/.test(t)&&$('#geneAxanthic').value==='unknown'){ $('#geneAxanthic').value='visual';found.push('비주얼 아잔틱') }if(/솔리드릴리|솔리드백|solidback|solidlilly/.test(t)){ $('#traitSolidBack').value='present';found.push('솔리드백') }if(/카푸치노|cappuccino/.test(t)){ $('#geneCappuccino').value='cappuccino';found.push('카푸치노') }const raw=$('#geckoNotation').value;const m=raw.match(/\(([^()]+)[\/×xX]([^()]+)\)/);if(m){const names=[m[1].trim(),m[2].trim()];const ids=names.map(n=>state.geckos.find(g=>g.name.trim()===n)?.id||'');if(ids[0]&&ids[1]){$('#geckoParent1').value=ids[0];$('#geckoParent2').value=ids[1];found.push(`부모 ${names[0]} / ${names[1]} 연결`)}}$('#notationHint').innerHTML=found.length?`인식: <b>${esc(found.join(' · '))}</b>`:'자동으로 확정할 수 있는 유전 표기를 찾지 못했습니다. 원문 표기는 그대로 저장됩니다.'}
function saveGecko(){const id=$('#geckoId').value,name=$('#geckoName').value.trim(),p1=$('#geckoParent1').value,p2=$('#geckoParent2').value,err=$('#geckoFormError');if(!name){err.textContent='이름을 입력하세요.';err.classList.remove('hidden');return}if(p1&&p1===p2){err.textContent='부모 두 칸에는 다른 개체를 선택하세요.';err.classList.remove('hidden');return}if(id&&((p1&&isAncestor(id,p1))||(p2&&isAncestor(id,p2)))){err.textContent='자기 자신이 자신의 조상이 되는 순환 가계도만 만들 수 없습니다.';err.classList.remove('hidden');return}const d=normalizeGecko({id:id||uid(),name,morph:$('#geckoMorph').value.trim(),sex:$('#geckoSex').value,hatchDate:$('#geckoHatchDate').value,acquiredDate:$('#geckoAcquiredDate').value,breeder:$('#geckoBreeder').value.trim(),notes:$('#geckoNotes').value.trim(),parent1Id:p1,parent2Id:p2,breederNotation:$('#geckoNotation').value.trim(),customTraits:splitTraits($('#geckoTraits').value),genetics:{lilly:$('#geneLilly').value,axanthic:$('#geneAxanthic').value,cappuccino:$('#geneCappuccino').value,solidBack:$('#traitSolidBack').value}});if(id)Object.assign(getGecko(id),d);else state.geckos.push(d);saveState();$('#geckoDialog').close();renderCurrent()}
function deleteGecko(id){if(!confirm(`“${geckoName(id)}”를 삭제할까요?`))return;state.geckos=state.geckos.filter(g=>g.id!==id);state.growth=state.growth.filter(r=>r.geckoId!==id);state.pairings=state.pairings.filter(p=>p.aId!==id&&p.bId!==id);state.geckos.forEach(g=>{if(g.parent1Id===id)g.parent1Id='';if(g.parent2Id===id)g.parent2Id=''});saveState();renderCurrent()}

function renderGrowth(){if(!growthSelectedGecko||!getGecko(growthSelectedGecko))growthSelectedGecko=state.geckos[0]?.id||'';const rows=state.growth.filter(r=>r.geckoId===growthSelectedGecko).sort((a,b)=>a.date.localeCompare(b.date));$('#view-growth').innerHTML=`<div class="card pad"><div class="section-head"><div><h2>성장 기록</h2></div><button class="btn primary" id="addGrowthInView" ${state.geckos.length?'':'disabled'}>+ 기록</button></div>${state.geckos.length?`<label>개체<select id="growthFocus">${state.geckos.map(g=>`<option value="${g.id}" ${g.id===growthSelectedGecko?'selected':''}>${esc(g.name)}</option>`).join('')}</select></label><div id="growthChart" class="chart-box" style="margin-top:18px">${growthChartSvg(rows)}</div>`:emptyHtml('먼저 개체를 등록하세요.')}</div><div class="card" style="margin-top:18px">${rows.length?`<div class="table-wrap"><table><thead><tr><th>날짜</th><th>체중</th><th>전장</th><th>상태</th><th>메모</th><th></th></tr></thead><tbody>${[...rows].reverse().map(r=>`<tr><td>${r.date}</td><td>${r.weight!==''?r.weight+' g':'-'}</td><td>${r.length!==''?r.length+' cm':'-'}</td><td>${esc(r.condition||'-')}</td><td>${esc(r.note||'-')}</td><td><button class="btn ghost small" data-rdel="${r.id}">삭제</button></td></tr>`).join('')}</tbody></table></div>`:emptyHtml('성장 기록이 없습니다.')}</div>`;if($('#growthFocus'))$('#growthFocus').onchange=e=>{growthSelectedGecko=e.target.value;renderGrowth()};if($('#addGrowthInView'))$('#addGrowthInView').onclick=()=>openGrowthDialog('',growthSelectedGecko);$$('[data-rdel]').forEach(b=>b.onclick=()=>{if(confirm('삭제할까요?')){state.growth=state.growth.filter(r=>r.id!==b.dataset.rdel);renderAll()}})}
function growthChartSvg(rows){const pts=rows.filter(r=>r.weight!==''&&r.weight!=null);if(pts.length<2)return emptyHtml('그래프 데이터가 부족합니다.','체중 기록이 2개 이상이면 선 그래프가 표시됩니다.');const W=800,H=260,P=40,vals=pts.map(x=>+x.weight),min=Math.min(...vals),max=Math.max(...vals),rng=max-min||1,x=i=>P+i*(W-2*P)/(pts.length-1),y=v=>H-P-(v-min)*(H-2*P)/rng,path=pts.map((r,i)=>`${i?'L':'M'} ${x(i)} ${y(r.weight)}`).join(' ');return `<svg class="chart-svg" viewBox="0 0 ${W} ${H}"><path class="chart-line" d="${path}"/>${pts.map((r,i)=>`<circle class="chart-dot" cx="${x(i)}" cy="${y(r.weight)}" r="4"><title>${r.date}: ${r.weight}g</title></circle>`).join('')}</svg>`}
function openGrowthDialog(id='',gid=''){if(!state.geckos.length)return alert('먼저 개체를 등록하세요.');const r=id?state.growth.find(x=>x.id===id):null;fillGeckoSelect($('#growthGecko'));$('#growthId').value=r?.id||'';$('#growthGecko').value=r?.geckoId||gid||growthSelectedGecko||state.geckos[0].id;$('#growthDate').value=r?.date||today();$('#growthWeight').value=r?.weight??'';$('#growthLength').value=r?.length??'';$('#growthCondition').value=r?.condition||'';$('#growthNote').value=r?.note||'';$('#growthDialog').showModal()}
function saveGrowth(){const gid=$('#growthGecko').value;if(!gid||!$('#growthDate').value)return alert('개체와 날짜를 선택하세요.');const id=$('#growthId').value,d={id:id||uid(),geckoId:gid,date:$('#growthDate').value,weight:$('#growthWeight').value===''?'':+$('#growthWeight').value,length:$('#growthLength').value===''?'':+$('#growthLength').value,condition:$('#growthCondition').value,note:$('#growthNote').value.trim()};if(id)Object.assign(state.growth.find(x=>x.id===id),d);else state.growth.push(d);growthSelectedGecko=gid;saveState();$('#growthDialog').close();setView('growth')}

function computeLevels(){const memo=new Map(),vis=new Set();function lv(id){if(memo.has(id))return memo.get(id);if(vis.has(id))return 0;vis.add(id);const g=getGecko(id),ps=[g?.parent1Id,g?.parent2Id].filter(Boolean);const v=ps.length?Math.max(...ps.map(lv))+1:0;vis.delete(id);memo.set(id,v);return v}state.geckos.forEach(g=>lv(g.id));return memo}
function renderPedigree(){$('#view-pedigree').innerHTML=`<div class="card pad"><div class="section-head"><div><h2>자동 가계도</h2><p>부모를 입력하면 세대별로 자동 재배치됩니다.</p></div><button class="btn primary" id="addPair">+ 교배 관계</button></div><div class="pedigree-wrap"><svg id="pedigreeSvg" class="pedigree-svg"></svg></div></div><div class="card" style="margin-top:18px" id="pairTable"></div>`;drawPedigree();renderPairTable();$('#addPair').onclick=()=>openPairDialog()}
function drawPedigree(){const svg=$('#pedigreeSvg');if(!state.geckos.length){svg.setAttribute('viewBox','0 0 900 420');svg.innerHTML='<text x="450" y="210" text-anchor="middle" fill="#718096">개체를 등록하면 가계도가 생성됩니다.</text>';return}const levels=computeLevels(),groups={};state.geckos.forEach(g=>(groups[levels.get(g.id)||0]??=[]).push(g));const W=1100,nodeW=170,nodeH=70,gapY=115,pos=new Map();Object.keys(groups).forEach(k=>{const l=+k,arr=groups[k],row=arr.length*nodeW+(arr.length-1)*35,start=(W-row)/2;arr.forEach((g,i)=>pos.set(g.id,{x:start+i*(nodeW+35),y:50+l*(nodeH+gapY)}))});const H=Math.max(420,120+(Math.max(...levels.values())+1)*(nodeH+gapY));const edges=[];state.geckos.forEach(c=>[c.parent1Id,c.parent2Id].filter(p=>pos.has(p)).forEach(pid=>{const a=pos.get(pid),b=pos.get(c.id),x1=a.x+nodeW/2,y1=a.y+nodeH,x2=b.x+nodeW/2,y2=b.y,m=(y1+y2)/2;edges.push(`<path class="pedge" d="M${x1} ${y1} C${x1} ${m},${x2} ${m},${x2} ${y2}"/>`)}));const pair=state.pairings.filter(p=>pos.has(p.aId)&&pos.has(p.bId)).map(p=>{const a=pos.get(p.aId),b=pos.get(p.bId);return `<path class="pair-edge" d="M${a.x+nodeW/2} ${a.y+nodeH/2} L${b.x+nodeW/2} ${b.y+nodeH/2}"/>`}).join('');const nodes=state.geckos.map(g=>{const p=pos.get(g.id);return `<g class="pnode" transform="translate(${p.x} ${p.y})"><rect width="${nodeW}" height="${nodeH}"/><text class="name" x="14" y="26">${esc(g.name)}</text><text class="meta" x="14" y="48">${esc(comboAliasesForGecko(g)[0]||g.morph||'모프 미입력')}</text><text class="meta" x="14" y="64">${sexLabel(g.sex)}</text></g>`}).join('');svg.setAttribute('viewBox',`0 0 ${W} ${H}`);svg.innerHTML=edges.join('')+pair+nodes}
function renderPairTable(){const el=$('#pairTable');el.innerHTML=state.pairings.length?`<div class="table-wrap"><table><thead><tr><th>A</th><th>B</th><th>관계</th><th>상태</th><th></th></tr></thead><tbody>${state.pairings.map(p=>`<tr><td>${esc(geckoName(p.aId))}</td><td>${esc(geckoName(p.bId))}</td><td>${esc(relationOf(p.aId,p.bId))}</td><td>${statusLabel(p.status)}</td><td><button class="btn ghost small" data-pdel="${p.id}">삭제</button></td></tr>`).join('')}</tbody></table></div>`:emptyHtml('등록된 교배 관계가 없습니다.');$$('[data-pdel]').forEach(b=>b.onclick=()=>{state.pairings=state.pairings.filter(p=>p.id!==b.dataset.pdel);renderAll()})}
function openPairDialog(){if(state.geckos.length<2)return alert('개체가 2마리 이상 필요합니다.');fillGeckoSelect($('#pairA'));fillGeckoSelect($('#pairB'));$('#pairA').value=state.geckos[0].id;$('#pairB').value=state.geckos[1].id;$('#pairId').value='';$('#pairDate').value=today();$('#pairStatus').value='planned';$('#pairNote').value='';updatePairHint();$('#pairA').onchange=updatePairHint;$('#pairB').onchange=updatePairHint;$('#pairDialog').showModal()}
function updatePairHint(){$('#pairRelationHint').innerHTML=`관계 판정: <b>${esc(relationOf($('#pairA').value,$('#pairB').value))}</b>`}
function savePair(){const a=$('#pairA').value,b=$('#pairB').value;if(!a||!b||a===b)return alert('서로 다른 두 개체를 선택하세요.');const A=getGecko(a),B=getGecko(b);if(A.sex!=='unknown'&&B.sex!=='unknown'&&A.sex===B.sex&&!confirm('두 개체의 성별이 동일하게 확정되어 있습니다. 그래도 기록할까요?'))return;state.pairings.push({id:uid(),aId:a,bId:b,date:$('#pairDate').value,status:$('#pairStatus').value,note:$('#pairNote').value.trim()});saveState();$('#pairDialog').close();renderPedigree()}

function explicitDist(g,gene){const v=g.genetics?.[gene];if(gene==='axanthic'){if(v==='visual')return{2:1};if(v==='het100')return{1:1};if(v==='het66')return{1:.66,0:.34};if(v==='het50')return{1:.5,0:.5};if(v==='clear')return{0:1}}else{if(v==='super')return{2:1};if(v==='lilly'||v==='cappuccino')return{1:1};if(v==='normal')return{0:1}}return null}
function inferredFromText(g,gene){const t=((g.morph||'')+' '+(g.breederNotation||'')).toLowerCase().replace(/\s/g,'');if(gene==='lilly'&&/릴잔틱|릴리아잔틱|릴리|lillywhite/.test(t))return{1:1};if(gene==='axanthic'){if(/100%?헷아잔틱/.test(t))return{1:1};if(/66%?헷아잔틱/.test(t))return{1:.66,0:.34};if(/50%?헷아잔틱/.test(t))return{1:.5,0:.5};if(/릴잔틱|릴리아잔틱|아잔틱|axanthic/.test(t))return{2:1}}if(gene==='cappuccino'&&/카푸치노|cappuccino|프라푸치노/.test(t))return{1:1};return null}
function gameteDist(copies){return copies===0?{0:1}:copies===1?{0:.5,1:.5}:{1:1}}
function crossDist(a,b){const out={0:0,1:0,2:0};Object.entries(a).forEach(([ca,pa])=>Object.entries(b).forEach(([cb,pb])=>{const ga=gameteDist(+ca),gb=gameteDist(+cb);Object.entries(ga).forEach(([xa,qa])=>Object.entries(gb).forEach(([xb,qb])=>out[+xa + +xb]+=pa*pb*qa*qb))}));return Object.fromEntries(Object.entries(out).filter(([,p])=>p>1e-9))}
function geneDist(g,gene,seen=new Set()){if(!g)return{0:1};const ex=explicitDist(g,gene);if(ex)return ex;const txt=inferredFromText(g,gene);if(txt)return txt;if(seen.has(g.id))return{0:1};seen.add(g.id);const p1=getGecko(g.parent1Id),p2=getGecko(g.parent2Id);if(p1&&p2)return crossDist(geneDist(p1,gene,new Set(seen)),geneDist(p2,gene,new Set(seen)));return{0:1}}
function offspringDist(A,B,gene){return crossDist(geneDist(A,gene),geneDist(B,gene))}
function childMorphAliases(l,a,c,solidPossible){const main=[];if(l===2)main.push('슈퍼 릴리');else if(l===1)main.push('릴리화이트');if(a===2)main.push('아잔틱');if(c===2)main.push('슈퍼 카푸치노');else if(c===1)main.push('카푸치노');let aliases=[];if(l===1&&a===2)aliases=['릴리아잔틱','릴잔틱','릴리 아잔틱','Lilly White Axanthic'];else if(l===1&&c===1)aliases=['프라푸치노','Frappuccino'];else if(l===1&&solidPossible)aliases=['솔리드릴리 가능','솔리드 릴리 가능','솔리드백 릴리 가능','Solid Lilly possible'];const genetic=[];if(a===1)genetic.push('100% 헷 아잔틱');return{title:aliases[0]||main.join(' + ')||'노멀/기타 표현형',aliases:aliases.slice(1),genetic}}
function renderGenetics(){const opts=state.geckos.map(g=>`<option value="${g.id}">${esc(g.name)} · ${sexLabel(g.sex)}</option>`).join('');$('#view-genetics').innerHTML=`<div class="card pad"><div class="section-head"><div><h2>두 개체 교배 예상</h2><p>성별 미확인은 수컷·암컷 어느 쪽으로도 선택할 수 있습니다. 릴리×릴리도 계산은 막지 않고 슈퍼 릴리 가능성을 표시합니다.</p></div></div>${state.geckos.length<2?emptyHtml('개체가 2마리 이상 필요합니다.'):`<div class="form-grid two"><label>개체 A<select id="genA">${opts}</select></label><label>개체 B<select id="genB">${opts}</select></label></div><div id="genResult" style="margin-top:18px"></div>`}</div>`;if(state.geckos.length>=2){$('#genA').value=state.geckos[0].id;$('#genB').value=state.geckos[1].id;$('#genA').onchange=renderGenResult;$('#genB').onchange=renderGenResult;renderGenResult()}}
function renderGenResult(){const A=getGecko($('#genA').value),B=getGecko($('#genB').value),el=$('#genResult');if(!A||!B||A.id===B.id){el.innerHTML='<div class="notice">서로 다른 두 개체를 선택하세요.</div>';return}const same=A.sex!=='unknown'&&B.sex!=='unknown'&&A.sex===B.sex;const ld=offspringDist(A,B,'lilly'),ad=offspringDist(A,B,'axanthic'),cd=offspringDist(A,B,'cappuccino');const solid=A.genetics.solidBack==='present'||B.genetics.solidBack==='present';const results=[];Object.entries(ld).forEach(([l,pl])=>Object.entries(ad).forEach(([a,pa])=>Object.entries(cd).forEach(([c,pc])=>{const p=pl*pa*pc;if(p<.0001)return;const nm=childMorphAliases(+l,+a,+c,solid);results.push({p,l:+l,a:+a,c:+c,...nm})})));results.sort((x,y)=>y.p-x.p);const assess=g=>{const a=geneticAssessment(g);return `<div class="card pad"><h3>${esc(g.name)}</h3><div class="muted">${sexLabel(g.sex)} · ${esc(comboAliasesForGecko(g).join(' / ')||g.morph||'모프 미입력')}</div><p><b>확실:</b> ${esc(a.certain.join(' · ')||'없음')}</p><p><b>가능:</b> ${esc(a.possible.join(' · ')||'없음')}</p></div>`};el.innerHTML=`${same?'<div class="notice danger">두 개체는 같은 성별로 확정되어 있어 실제 교배 대상은 아닙니다. 유전 계산 자체는 참고용으로 표시합니다.</div>':''}${(ld[2]||0)>0?'<div class="notice danger"><b>슈퍼 릴리 가능성이 포함됩니다.</b> 계산 결과에서는 제외하지 않고 그대로 표시합니다.</div>':''}<div class="grid cols-2">${assess(A)}${assess(B)}</div><div class="card" style="margin-top:18px"><div class="section-head" style="padding:18px 18px 0"><div><h2>예상 자손</h2><p>유전적으로 계산 가능한 릴리화이트·아잔틱·카푸치노를 조합한 결과입니다. 솔리드백은 정확한 멘델 확률 대신 가능성만 덧붙입니다.</p></div></div><div class="table-wrap"><table><thead><tr><th>확률</th><th>예상 모프 / 통용명</th><th>유전 상태</th><th>비고</th></tr></thead><tbody>${results.map(r=>`<tr><td><b>${pct(r.p)}</b></td><td class="name-cell"><b>${esc(r.title)}</b><span>${esc(r.aliases.join(' / '))}</span></td><td>${esc([r.a===1?'100% 헷 아잔틱':'',r.a===2?'비주얼 아잔틱':'',r.l===2?'슈퍼 릴리':'',r.c===2?'슈퍼 카푸치노':''].filter(Boolean).join(' · ')||'-')}</td><td>${r.l===2?'<span class="badge warn">슈퍼 릴리</span>':solid?'<span class="badge unknown">솔리드백 표현 가능성</span>':'-'}</td></tr>`).join('')}</tbody></table></div></div>`}

function renderBackup(){const size=new Blob([JSON.stringify(state)]).size;$('#view-backup').innerHTML=`<div class="backup-grid"><div class="card backup-card"><h3>JSON 백업</h3><p>개체·성장·유전·가계도 데이터를 저장합니다.</p><button class="btn primary" id="exportBtn">백업 파일 다운로드</button></div><div class="card backup-card"><h3>JSON 복원</h3><p>기존 백업도 자동 마이그레이션합니다.</p><button class="btn secondary" id="importBtn">백업 파일 불러오기</button></div><div class="card backup-card"><h3>전체 초기화</h3><p>브라우저의 모든 기록을 삭제합니다.</p><button class="btn danger" id="resetBtn">모든 데이터 삭제</button></div></div><div class="card pad" style="margin-top:18px">개체 ${state.geckos.length}마리 · 성장 ${state.growth.length}개 · 교배 ${state.pairings.length}개 · ${(size/1024).toFixed(1)} KB</div>`;$('#exportBtn').onclick=exportData;$('#importBtn').onclick=()=>$('#importFile').click();$('#resetBtn').onclick=()=>{if(confirm('모든 데이터를 삭제할까요?')){state.geckos=[];state.growth=[];state.pairings=[];saveState();renderCurrent()}}}
function exportData(){const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString(),app:'Crestie Lineage',version:2},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`crestie-lineage-v2-${today()}.json`;a.click();URL.revokeObjectURL(u)}
function importData(f){const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(!Array.isArray(p.geckos))throw 0;if(!confirm('현재 데이터를 백업 파일 내용으로 바꿀까요?'))return;state.geckos=p.geckos.map(normalizeGecko);state.growth=Array.isArray(p.growth)?p.growth:[];state.pairings=Array.isArray(p.pairings)?p.pairings:[];saveState();renderCurrent()}catch{alert('올바른 백업 파일이 아닙니다.')}};r.readAsText(f)}

$$('.nav-btn').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#quickGeckoBtn').onclick=()=>openGeckoDialog();$('#quickGrowthBtn').onclick=()=>openGrowthDialog('',growthSelectedGecko);$('#saveGeckoBtn').onclick=saveGecko;$('#saveGrowthBtn').onclick=saveGrowth;$('#savePairBtn').onclick=savePair;$('#analyzeNotationBtn').onclick=analyzeNotation;$('#importFile').onchange=e=>{const f=e.target.files?.[0];if(f)importData(f);e.target.value=''};renderDashboard();
